### ISSUE TITLE
-h / --help reporting an error... but working

### ISSUE THREAD

**Issue by JJ** [azohra/yaml.sh#13]
**Describe the bug**

When I run `ysh -h` or `ysh --help` in zsh, it reports:

```
Unknown option: -h Refer to -h for help.
```

**To Reproduce**

**Screenshots**
![Captura de pantalla de 2020-12-06 18-43-14](https://user-images.githubusercontent.com/500/101287808-ee074800-37f2-11eb-9641-c93d79b27cc4.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 20.04
Latest

**Comment by fvumbaca** [comment]
Hello and thanks for the issue!

Sorry about the super late reply. I just opened and linked an MR to fix this issue.
