### ISSUE TITLE
Support for better error handline.

### ISSUE THREAD

**Issue by NexthinkGuru** [azohra/yaml.sh#16]
**Is your feature request related to a problem? Please describe.**
Currently, all of the logic on valid file existence, valid path, readable file, etc is external to the solution.  If the filename passed isn't readable, awk will attempt the read, generate an error yet return a zero exit code value.  Checking for non 0 error codes isn't possible as a library function call. 

**Describe the solution you'd like**
 It would be helpful to return a non zero error code if the filename is not valid.

**Describe alternatives you've considered**
Currently we manage all of this external to ysh.

**Additional context**

**Comment by fvumbaca** [comment]
Hey! Thanks for your issue! Sorry for the long wait time. I created #17  that should give you the correct error output and exit code.
